name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-backend:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: test
      # Usar Secrets de GitHub para las variables sensibles es la mejor práctica
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      JWT_REFRESH_SECRET: ${{ secrets.JWT_REFRESH_SECRET }}
      PORT: 3002
    
    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js 20.x
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'
        cache: 'npm'
        cache-dependency-path: backend/package-lock.json

    - name: Install Tesseract OCR
      run: |
        sudo apt-get update
        sudo apt-get install -y tesseract-ocr tesseract-ocr-spa
        echo "✅ Tesseract OCR instalado"

    - name: Install backend dependencies
      # Usa 'npm ci' para una instalación limpia y reproducible
      run: npm ci
      working-directory: ./backend

    - name: Run backend tests
      # Usa 'npm test' si tienes el script de tests en tu package.json.
      # Esto es más portable y menos propenso a errores.
      run: npm test
      working-directory: ./backend

    - name: Upload coverage reports
      uses: codecov/codecov-action@v3
      with:
        files: ./backend/coverage/lcov.info
        flags: backend
        fail_ci_if_error: false