name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'
        cache: 'npm'
        cache-dependency-path: backend/package-lock.json

    - name: Install Tesseract
      run: sudo apt-get install -y tesseract-ocr tesseract-ocr-spa

    - name: Install dependencies
      run: |
        cd backend
        npm install

    # ✅ EJECUTAR JEST DIRECTAMENTE
    - name: Run tests
      run: |
        cd backend
        npx jest --config jest.config.js --runInBand --detectOpenHandles

    - name: Upload coverage
      uses: codecov/codecov-action@v3
      with:
        file: ./backend/coverage/lcov.info