name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-backend:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]  # ✅ CAMBIADO: Solo Node 20.x

    env:
      NODE_ENV: test
      JWT_SECRET: test_jwt_secret_super_seguro_para_pruebas_12345
      JWT_REFRESH_SECRET: test_refresh_secret_super_seguro_para_pruebas_67890
      PORT: 3002

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: backend/package-lock.json

    - name: Install Tesseract OCR
      run: |
        sudo apt-get update
        sudo apt-get install -y tesseract-ocr tesseract-ocr-spa
        echo "✅ Tesseract OCR instalado"
        tesseract --version

    - name: Install backend dependencies
      run: |
        cd backend
        npm install

    - name: Create test environment file
      run: |
        cd backend
        echo "NODE_ENV=test" > .env.test
        echo "JWT_SECRET=test_jwt_secret_super_seguro_para_pruebas_12345" >> .env.test
        echo "JWT_REFRESH_SECRET=test_refresh_secret_super_seguro_para_pruebas_67890" >> .env.test
        echo "PORT=3002" >> .env.test
        echo "COOKIE_DOMAIN=localhost" >> .env.test

    - name: Run tests
      run: |
        cd backend
        npm test

    - name: Upload coverage reports
      uses: codecov/codecov-action@v3
      with:
        file: ./backend/coverage/lcov.info
        flags: backend
        fail_ci_if_error: false