name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-backend:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: test
      JWT_SECRET: test_jwt_secret_super_seguro_para_pruebas_12345
      JWT_REFRESH_SECRET: test_refresh_secret_super_seguro_para_pruebas_67890
      PORT: 3002

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js 20.x
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'
        cache: 'npm'
        cache-dependency-path: backend/package-lock.json

    - name: Install Tesseract OCR
      run: |
        sudo apt-get update
        sudo apt-get install -y tesseract-ocr tesseract-ocr-spa
        echo "✅ Tesseract OCR instalado"
        tesseract --version

    - name: Install backend dependencies
      run: |
        cd backend
        npm install

    # ✅ SOLUCIÓN: Dar permisos de ejecución a los binarios de node_modules
    - name: Fix permissions for node_modules
      run: |
        cd backend
        chmod -R +x node_modules/.bin/
        ls -la node_modules/.bin/ | grep jest  # Verificar que jest tenga permisos

    - name: Create test environment file
      run: |
        cd backend
        echo "NODE_ENV=test" > .env.test
        echo "JWT_SECRET=test_jwt_secret_super_seguro_para_pruebas_12345" >> .env.test
        echo "JWT_REFRESH_SECRET=test_refresh_secret_super_seguro_para_pruebas_67890" >> .env.test
        echo "PORT=3002" >> .env.test
        echo "COOKIE_DOMAIN=localhost" >> .env.test

    - name: Run tests
      run: |
        cd backend
        npx jest --config jest.config.js --runInBand --detectOpenHandles

    - name: Upload coverage reports
      uses: codecov/codecov-action@v3
      with:
        file: ./backend/coverage/lcov.info
        flags: backend
        fail_ci_if_error: false